// <auto-generated />
using System;
using EFProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFProject.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230106221411_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFProject.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("ed3c3bc7-7e9c-450f-b069-72dcd2712149"),
                            Nombre = "Terminar cursos",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("ed3c3bc7-7e9c-450f-b069-72dcd2712145"),
                            Nombre = "Escuela",
                            Peso = 10
                        });
                });

            modelBuilder.Entity("EFProject.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("6661ba23-84e5-461c-aa2e-c5d12c97eaef"),
                            CategoriaId = new Guid("ed3c3bc7-7e9c-450f-b069-72dcd2712149"),
                            FechaCreacion = new DateTime(2023, 1, 6, 16, 14, 11, 447, DateTimeKind.Local).AddTicks(8877),
                            PrioridadTarea = 1,
                            Titulo = "Terminar curso de EF"
                        },
                        new
                        {
                            TareaId = new Guid("f6372f56-0b65-4550-8054-ec91070ba136"),
                            CategoriaId = new Guid("ed3c3bc7-7e9c-450f-b069-72dcd2712145"),
                            FechaCreacion = new DateTime(2023, 1, 6, 16, 14, 11, 447, DateTimeKind.Local).AddTicks(8925),
                            PrioridadTarea = 2,
                            Titulo = "Recoger titulo fisico"
                        });
                });

            modelBuilder.Entity("EFProject.Models.Tarea", b =>
                {
                    b.HasOne("EFProject.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("EFProject.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
